changelog:
  exclude:
    labels:
      - tooling
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes and Improvements
      labels:
        - bug
    - title: Documentation Changes
      labels:
        - documentation
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
