changelog:
  exclude:
    labels:
      - tooling
  categories:
    - title: Breaking Changes
      bump: major
      labels:
        - breaking
    - title: New Features
      bump: minor
      labels:
        - enhancement
    - title: Bug Fixes and Improvements
      bump: patch
      labels:
        - bug
    - title: Documentation Changes
      labels:
        - documentation
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
