name: Build
on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]
jobs:
  crate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: []
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: freight-${{ github.ref_name }}-${{ matrix.target }}
          path: target/release
      - run: cargo publish --target ${{ matrix.target }}
        if: github.ref_type == 'tag'
  release:
    runs-on: ubuntu-latest
    needs: [crate]
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*.zip