name: Build
on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches: ['**']
    tags: [v*]
  pull_request:
    branches: [main]
    types: [opened]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  crate:
    strategy:
      matrix:
        os:
        - ubuntu
        - macos
        - windows
    runs-on: ${{ matrix.os }}-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo build --release
      - run: cargo test
      - run: cargo bench
      - uses: actions/upload-artifact@v3
        with:
          name: freight-${{ github.head_ref || github.ref_name }}-${{ matrix.os }}
          path: target/release
      - run: cargo package
      - run: cargo publish
        if: github.ref_type == 'tag'
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
  image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: github.ref_type == 'tag'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  release:
    runs-on: ubuntu-latest
    needs: [crate, image]
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*