name: Build
on:
  workflow_dispatch:
  push:
    branches: ['**']
    tags: [v*]
    paths-ignore: [formula/**]
  pull_request:
    branches: [main]
    types: [opened]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn
      - run: yarn typecheck
      - run: yarn prettier --check .
      - run: yarn lint
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo test
      - run: cargo bench
      - run: cargo fmt --check
      - run: cargo clippy
  crate:
    needs: [lint, test]
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux
          - build: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # macos
          - build: darwin-amd64
            runner: macos-latest
            target: x86_64-apple-darwin
          - build: darwin-arm64
            runner: macos-latest
            target: aarch64-apple-darwin
          # windows
          - build: windows-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
    name: crate (${{ matrix.build }})
    runs-on: ${{ matrix.runner }}
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --target ${{ matrix.target }}
      - uses: actions/upload-artifact@v3
        with:
          name: freight-${{ github.head_ref || github.ref_name }}-${{ matrix.build }}
          path: |
            target/
            lib/
      - if: github.ref_type == 'tag'
        run: cargo publish
  image:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ github.repository }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - if: github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: github.ref_type == 'tag'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  docs:
    runs-on: ubuntu-latest
    needs: [lint, test]
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/configure-pages@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: cargo rustdoc
      - run: mv target/doc static/crates
      - run: yarn
      - run: yarn build
      - uses: actions/upload-pages-artifact@v2
        with:
          path: build
  deploy:
    runs-on: ubuntu-latest
    needs: [docs]
    if: github.ref_name == 'main' || github.ref_type == 'tag'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      contents: read
      id-token: write
    steps:
      - uses: actions/deploy-pages@v2
        id: deployment
  release:
    runs-on: ubuntu-latest
    needs: [crate, image, docs]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist/
      - if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: dist/*
      - if: github.ref_type == 'tag'
        uses: Justintime50/homebrew-releaser@v1
        with:
          homebrew_owner: tubbo
          homebrew_tap: freight
          github_token: ${{ github.token }}
          commit_owner: ${{ github.actor }}
          commit_email: ${{ github.actor }}@users.noreply.github.com
          install: |
            bin.install 'freight'
            lib.install Dir['lib/**']
            man.install Dir['man/**']
          target_darwin_amd64: true
          target_darwin_arm64: true
          target_linux_amd64: true
