name: Version
on:
  push:
    branches: [main]
  pull_request:
    types: [labeled]
jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: tubbo/action-bumpr@custom-labels
        with:
          major_labels: breaking
          minor_labels: enhancement
          patch_labels: bug,documentation
          tag_as_user: ${{ github.actor }}
          tag_as_email: ${{ github.actor }}@users.noreply.github.com
          version_file: Cargo.toml
